-- 003_weekly_pipeline.sql
-- ----------------------------------------------------------------------------
-- Additive schema for the rebuilt weekly pipeline (scripts/weekly). Creates new
-- tables only; the four existing weekly tables (seo_runs, weekly_posts,
-- website_tasks, run_logs) are untouched, and nothing here is read by the
-- legacy pipeline, mav-bridge, or gbp-worker. Reversible by dropping the
-- objects listed at the bottom. Idempotent: safe to re-run.
--
-- Plan of record: docs/rebuild/2026-09-06-weekly-pipeline-rebuild-plan.md
-- Contracts:      scripts/weekly/DESIGN.md (AttemptSchema, RevisionSchema,
--                 PlanItemSchema, ObservationSchema)
--
-- Security: RLS enabled on every new table with service-role-only access.
-- Unlike the existing tables there is deliberately NO anon read policy; these
-- are operational records. Add one later if a dashboard needs them.
-- ----------------------------------------------------------------------------

begin;

-- 1. Attempts: one row per pipeline attempt (an immutable id per run of run.mjs).
create table if not exists seo_attempts (
  id            text primary key,                 -- attempt id generated by the app
  week_of       date not null,                    -- Monday; same key as seo_runs.week_of
  mode          text not null,                    -- legacy | shadow | new | offline
  git_sha       text,
  versions      jsonb not null default '{}'::jsonb,   -- { schema, prompt, policy }
  models        jsonb not null default '{}'::jsonb,   -- { generate, fallback }
  started_at    timestamptz not null,
  finished_at   timestamptz,
  stages        jsonb not null default '{}'::jsonb,   -- { [stage]: { started_at, finished_at, status, error } }
  lease_until   timestamptz,
  budget_usd    numeric(10,4) not null default 0,
  spent_usd     numeric(10,4) not null default 0,
  status        text not null default 'running',      -- running | succeeded | degraded | failed
  error         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists idx_seo_attempts_week_of on seo_attempts(week_of desc, started_at desc);

-- 2. Week leases: at most one live attempt per week. Acquired atomically via
--    acquire_week_lease() below; expired leases can be taken over.
create table if not exists seo_week_leases (
  week_of      date primary key,
  attempt_id   text not null,
  lease_until  timestamptz not null,
  updated_at   timestamptz not null default now()
);

-- 3. Research observations: every input the pipeline looked at, with provenance.
create table if not exists research_observations (
  id            text primary key,
  attempt_id    text not null references seo_attempts(id) on delete cascade,
  source        text not null,      -- search_console | facebook | serpapi | history | facts | trends
  scope         text not null,      -- query, post id, url, topic
  geography     text,
  period_start  date,
  period_end    date,
  status        text not null,      -- ok | unavailable | error
  metric        text,
  value         jsonb,
  raw_ref       text,
  retrieved_at  timestamptz not null,
  note          text,
  created_at    timestamptz not null default now()
);
create index if not exists idx_research_obs_attempt on research_observations(attempt_id);
create index if not exists idx_research_obs_source  on research_observations(source, retrieved_at desc);

-- 4. Plan revisions: one validated, staged plan per attempt (revision n per week).
create table if not exists plan_revisions (
  id            text primary key,
  attempt_id    text not null references seo_attempts(id) on delete cascade,
  week_of       date not null,
  revision      int  not null,
  topic         jsonb not null,
  selection     jsonb not null,
  validation    jsonb not null,     -- { ok, errors[], warnings[] }
  exported_at   timestamptz,
  projected_at  timestamptz,        -- set when items were projected into weekly_posts / website_tasks
  created_at    timestamptz not null default now(),
  unique (week_of, revision)
);
create index if not exists idx_plan_revisions_week on plan_revisions(week_of desc, revision desc);

-- 5. Plan items: the content units of a revision (7 GBP, 4 Facebook, n website).
create table if not exists plan_items (
  id               text primary key,
  revision_id      text not null references plan_revisions(id) on delete cascade,
  platform         text not null,   -- gbp | facebook | website
  slot_date        date,
  item_type        text not null,
  content          jsonb not null,
  media_ref        text,
  idempotency_key  text not null,
  projected_ref    text,            -- weekly_posts.id or website_tasks.id once projected
  publish_status   text,            -- copied back by reconcile
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (revision_id, idempotency_key)
);
create index if not exists idx_plan_items_revision on plan_items(revision_id);
create index if not exists idx_plan_items_slot     on plan_items(platform, slot_date);
create index if not exists idx_plan_items_projected on plan_items(projected_ref);

-- 6. Performance observations: metrics per item, page, or profile over a window.
create table if not exists performance_observations (
  id                uuid primary key default gen_random_uuid(),
  plan_item_id      text references plan_items(id) on delete set null,
  platform_post_id  text,
  page_url          text,
  metric            text not null,
  window_days       int,
  source            text not null,  -- facebook | search_console | gbp
  value             numeric,
  availability      text not null default 'ok',   -- ok | unavailable | not_mature
  paid              boolean not null default false,
  measured_at       timestamptz not null,
  created_at        timestamptz not null default now()
);
create index if not exists idx_perf_obs_item    on performance_observations(plan_item_id);
create index if not exists idx_perf_obs_post    on performance_observations(platform_post_id);
create index if not exists idx_perf_obs_metric  on performance_observations(metric, measured_at desc);

-- updated_at maintenance (set_updated_at() exists from schema.sql; recreate defensively).
create or replace function set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
create or replace trigger seo_attempts_updated_at
  before update on seo_attempts for each row execute function set_updated_at();
create or replace trigger seo_week_leases_updated_at
  before update on seo_week_leases for each row execute function set_updated_at();
create or replace trigger plan_items_updated_at
  before update on plan_items for each row execute function set_updated_at();

-- 7. Atomic lease acquisition. Returns ok=true when the caller now holds the
--    lease (fresh, expired takeover, or re-entry by the same attempt).
create or replace function acquire_week_lease(p_week_of date, p_attempt_id text, p_ttl_seconds int)
returns table (ok boolean, holder text, lease_until timestamptz)
language plpgsql set search_path = public as $$
declare
  v_row seo_week_leases%rowtype;
begin
  insert into seo_week_leases (week_of, attempt_id, lease_until)
  values (p_week_of, p_attempt_id, now() + make_interval(secs => p_ttl_seconds))
  on conflict (week_of) do update
    set attempt_id  = excluded.attempt_id,
        lease_until = excluded.lease_until
    where seo_week_leases.lease_until < now()
       or seo_week_leases.attempt_id = excluded.attempt_id
  returning * into v_row;

  if v_row.week_of is null then
    select * into v_row from seo_week_leases where week_of = p_week_of;
    return query select false, v_row.attempt_id, v_row.lease_until;
  else
    return query select true, v_row.attempt_id, v_row.lease_until;
  end if;
end;
$$;

create or replace function release_week_lease(p_week_of date, p_attempt_id text)
returns boolean language plpgsql set search_path = public as $$
declare
  v_count int;
begin
  delete from seo_week_leases where week_of = p_week_of and attempt_id = p_attempt_id;
  get diagnostics v_count = row_count;
  return v_count > 0;
end;
$$;

-- 8. Transactional staging: a revision and all of its items land together or
--    not at all. p_items is a JSON array of plan_items rows (without revision_id).
create or replace function stage_plan_revision(p_revision jsonb, p_items jsonb)
returns text language plpgsql set search_path = public as $$
declare
  v_id text := p_revision->>'id';
begin
  insert into plan_revisions (id, attempt_id, week_of, revision, topic, selection, validation, exported_at, projected_at)
  values (
    v_id,
    p_revision->>'attempt_id',
    (p_revision->>'week_of')::date,
    (p_revision->>'revision')::int,
    coalesce(p_revision->'topic', '{}'::jsonb),
    coalesce(p_revision->'selection', '{}'::jsonb),
    coalesce(p_revision->'validation', '{}'::jsonb),
    nullif(p_revision->>'exported_at', '')::timestamptz,
    nullif(p_revision->>'projected_at', '')::timestamptz
  );

  insert into plan_items (id, revision_id, platform, slot_date, item_type, content, media_ref, idempotency_key, projected_ref, publish_status)
  select
    i->>'id',
    v_id,
    i->>'platform',
    nullif(i->>'slot_date', '')::date,
    i->>'item_type',
    coalesce(i->'content', '{}'::jsonb),
    nullif(i->>'media_ref', ''),
    i->>'idempotency_key',
    nullif(i->>'projected_ref', ''),
    nullif(i->>'publish_status', '')
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) as i;

  return v_id;
end;
$$;

-- 9. Row-level security: service role only. No anon policies on purpose.
alter table seo_attempts             enable row level security;
alter table seo_week_leases          enable row level security;
alter table research_observations    enable row level security;
alter table plan_revisions           enable row level security;
alter table plan_items               enable row level security;
alter table performance_observations enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array['seo_attempts','seo_week_leases','research_observations','plan_revisions','plan_items','performance_observations']
  loop
    if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = t and policyname = 'Service role full access') then
      execute format('create policy "Service role full access" on %I for all using (auth.role() = ''service_role'')', t);
    end if;
  end loop;
end $$;

commit;

-- Rollback (manual, in this order):
--   drop function if exists stage_plan_revision(jsonb, jsonb);
--   drop function if exists release_week_lease(date, text);
--   drop function if exists acquire_week_lease(date, text, int);
--   drop table if exists performance_observations, plan_items, plan_revisions,
--     research_observations, seo_week_leases, seo_attempts;
